### ISSUE TITLE
IDOR

### ISSUE THREAD

**Issue by Srujana2505** [opencodeiiita/PhotoStore#40]
# Task
Hey contributors, the first **cybersec** issue is here.
The web application doesn't seem safe for **private** images. We need you to find the bug and patch it. 

# Steps
- Clone the repository after forking it
- Find the bug and patch it
- Create a PR to the **'main'** branch

# Rules
This is an **open to all** issue. So no need to **claim** it, just making a *proper PR* would be enough.

We follow **FCFS**, **F**irst **C**ome **F**irst **S**erve

We will give points to the contributor who makes **the first valid PR**
However, if we aren't satisfied with it we may reject it and consider other PRs.

*So keep your modifications clean and meaningful.*

Follow [README.md](https://github.com/opencodeiiita/PhotoStore/blob/main/README.md) to get started.

**NOTE:** this Issue is restricted to the **main** branch
You are requested to create a Pull request for that branch (main) only

**Comment by Monik09** [comment]
claim

**Comment by jalanprakhar** [comment]
claim
