### ISSUE TITLE
Trending photos

### ISSUE THREAD

**Issue by Srujana2505** [opencodeiiita/PhotoStore#72]
## Task

Regarding the website in this project, we require a feature to allow the users to see **Trending photos**
throughout the community on **Main page**.

## Steps
- Clone the repository after forking it
- Switch to `dev` branch
- Implement the feature
- Create a Pull request

For new users, go through [README.md](https://github.com/opencodeiiita/PhotoStore/blob/dev/README.md#setup) for instructions on how to set up this project locally

## Rules
We follow **FCFS**, **F**irst **C**ome **F**irst **S**erve

The **first** user **to claim** this Issue gets the chance to work on it
The assignee gets **2 days** to solve the Issue

If a user doesn't respond or solve the Issue
the mentor may **unassign** them from the Issue and allow another user to work on it.

At the end, we will select an appropriate PR.
So keep your modifications clean and meaningful.

**To claim**, simply comment with any of the following terms
- I would like to work on this feature
- May I claim this Issue?
- Claim

**NOTE**: this Issue is restricted to the [dev](https://github.com/opencodeiiita/PhotoStore/tree/dev) branch
You are requested to create a **Pull request** for that branch (`dev`) only

**Comment by Monik09** [comment]
claim

**Comment by Monik09** [comment]
@Srujana2505 i have removed my assignment.

**Comment by Ksathwik03** [comment]
Claim
