### ISSUE TITLE
Bug in likes

### ISSUE THREAD

**Issue by Ksathwik03** [opencodeiiita/PhotoStore#76]
When a user dislikes a photo and reloads the page the total likes are not reduced.
Also in this case the user is not able to relike again.
Detailed video is attached below.
https://user-images.githubusercontent.com/76401429/136687795-2844bd0d-6e42-4025-8a61-561d2314a1ab.mp4

**Comment by criticic** [comment]
those images are staring into my soul

**Comment by Mitul16** [comment]
@Ksathwik03 It is working for me. I can't find any issues.
