### ISSUE TITLE
Sorting of images by likes, views, time of upload

### ISSUE THREAD

**Issue by Mitul16** [opencodeiiita/PhotoStore#82]
## Task
We require an option on the pages that show images - `/`, `/profile`, `/community`
to allow the user to sort images in ascending, descending order of *likes*, *views*, *time at which the given image was uploaded*

Show a **dropdown menu** to select the field to sort with along with the order to follow - `ASC` or `DESC`
You may select any suitable method to present it to the user whether it be a dropdown menu or icons

## Steps
- Fork this repository
- Clone the forked repository
- Switch to `dev` branch
- Implement the feature
- Create a Pull request

For new users, go through [README.md](https://github.com/opencodeiiita/PhotoStore/blob/dev/README.md#setup) for instructions on how to set up this project locally

## Rules
We follow **FCFS**, **F**irst **C**ome **F**irst **S**erve

The **first** user **to claim** this Issue gets the chance to work on it
The assignee gets **2 days** to solve the Issue

If a user doesn't respond or solve the Issue
the mentor may **unassign** them from the Issue
and allow another user to work on it.

At the end, we will only select the appropriate PR.
So keep your modifications clean and meaningful.

**To claim**, simply comment with any of the following terms
- I would like to work on this feature
- May I claim this Issue?
- Claim

**NOTE**: this Issue is restricted to the [dev](https://github.com/opencodeiiita/PhotoStore/tree/dev) branch
You are requested to create a **Pull request** for that branch (`dev`) only

**Comment by rushilpatra** [comment]
Claim
