### ISSUE TITLE
Allow users to comment on a photo

### ISSUE THREAD

**Issue by Mitul16** [opencodeiiita/PhotoStore#87]
## Task
Similar to how **likes** feature is implemented, add an option to allow users to *comment on a photo*
Try to keep your frontend visuals similar to the `who-liked` container available in an image container.

### Layout
On the left side of an image container, we can show `who-commented` container

You may want to shift the `views` and `likes` boxes and add another `comments` box
Such that you have the following layout for the `image-overlay-container`
```md
Username                             Time
-----------------------------------------
#Comments |       #Views       |   #Likes
-----------------------------------------
          |                    |
Comments  |                    |    Likes
          |                    |
-----------------------------------------
```

### Format of a comment
Try to use the following format
```md
Username                             Time
Comment...
```

## Steps
- Fork this repository
- Clone the forked repository
- Switch to `dev` branch
- Implement the feature
- Create a Pull request

For new users, go through [README.md](https://github.com/opencodeiiita/PhotoStore/blob/dev/README.md#setup) for instructions on how to set up this project locally

## Rules
We follow **FCFS**, **F**irst **C**ome **F**irst **S**erve

The **first** user **to claim** this Issue gets the chance to work on it
The assignee gets **2 days** to solve the Issue

If a user doesn't respond or solve the Issue the mentor may **unassign** them from the Issue
and allow another user to work on it.

At the end, we will only select the appropriate PR.
So keep your modifications clean and meaningful.

**To claim**, simply comment with any of the following terms
- I would like to work on this feature
- May I claim this Issue?
- Claim

**NOTE**: this Issue is restricted to the [dev](https://github.com/opencodeiiita/PhotoStore/tree/dev) branch
You are requested to create a **Pull request** for that branch (`dev`) only

**Comment by daniel-aracquine** [comment]
claim
