### ISSUE TITLE
Add 'Reset password' page

### ISSUE THREAD

**Issue by Mitul16** [opencodeiiita/PhotoStore#90]
## Task
Currently, there isn't any way for a user to reset their password once they have created their account.
Similar to `/signup` and `/login` pages, add `/resetpassword` page to allow the user to reset their password

Use the following input fields
- current password
- new password
- new password (again)

Make sure to include `CAPTCHA` (*currently it is disabled*) and all other checks that are being performed in `/login`
You may add a **Reset password** link within the **profile container** on `/profile`, the one holding `username` and their `avatar`

You are requested to not add any additional CSS styles for things that are already available in the current project.
Don't **just** complete the Issue by polluting code.

## Steps
- Fork this repository
- Clone the forked repository
- Switch to `dev` branch
- Implement the feature
- Create a Pull request

For new users, go through [README.md](https://github.com/opencodeiiita/PhotoStore/blob/dev/README.md#setup) for instructions on how to set up this project locally

## Rules
We follow **FCFS**, **F**irst **C**ome **F**irst **S**erve

The **first** user **to claim** this Issue gets the chance to work on it
The assignee gets **2 days** to solve the Issue

If a user doesn't respond or solve the Issue the mentor may **unassign** them from the Issue
and allow another user to work on it.

At the end, we will only select the appropriate PR.
So keep your modifications clean and meaningful.

**To claim**, simply comment with any of the following terms
- I would like to work on this feature
- May I claim this Issue?
- Claim

**NOTE**: this Issue is restricted to the [dev](https://github.com/opencodeiiita/PhotoStore/tree/dev) branch
You are requested to create a **Pull request** for that branch (`dev`) only

**Comment by raghavgoel25** [comment]
claim

**Comment by KIRTEE-TECH** [comment]
claim
